// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naaohlrbreowzrjdwxje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hYW9obHJicmVvd3pyamR3eGplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjAzMjQsImV4cCI6MjA3MTQ5NjMyNH0.s9LJw5YTMtLVoxkDW2IM1Oj99xOPmktoLInni5_zfh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});